### ISSUE TITLE
Plugin Config-Page not accessable after update

### ISSUE THREAD

**Issue by loxatsonnenberg** [christianTF/LoxBerry-Plugin-Any#13]
after update to Pre-Release V0.3.0 there is no access to the plugin configuration page possible any more.

The link /admin/plugins/anyplugin/ is showing only the LB plugin overview page /admin/system/index.cgi

**Comment by christianTF** [comment]
Don't know how, but have over written the Index.cgi.
I cannot revert the commit on the tablet, will fix this in the morning.
Thanks for your issue!

**Comment by christianTF** [comment]
Fixed by https://github.com/christianTF/LoxBerry-Plugin-Any/commit/2e0a1a2f6f3f514e0afd24362926c4683506343e
